// Gold Sniper v2.4.1 Config (GitHub Pages safe)
window.CONFIG = {
  PROXY_URL: "https://gold-sniper-proxy.dvdndng.workers.dev",
  USD_PROXY_SYMBOL: "EUR/USD",
  GOLD_SYMBOL: "XAU/USD",
  TREND_INTERVAL: "5min",
  TREND_LOOKBACK_BARS: 12,
  LEVELS_H1_INTERVAL: "1h",
  LEVELS_M15_INTERVAL: "15min",
  TZ_OFFSET_MINUTES: 180,
  LONDON_START: "08:00",
  LONDON_MINUTES: 180,
  NY_START: "13:30",
  NY_MINUTES: 180,
  ALERTS_DEFAULT: "off",
  ALERT_COOLDOWN_SECONDS: 120,
  NEWS_PRE_MINUTES: 60,
  NEWS_POST_MINUTES: 60,
  NEWS_AUTO_DEFAULT: "on",
  NEWS_AUTO_COUNT: 8
};
